### ISSUE TITLE
Drop assisted key derivation support

### ISSUE THREAD

**Issue by bitgamma** [status-im/hardware-wallet#14]
The assisted key derivation functionality is needed to support cards without KeyAgreement.ALG_EC_SVDP_DH_PLAIN_XY. This was implemented because no card actually implemented that and we will wanted to do BIP-32.

However, it is a workaround and it is not strictly necessary anymore. Removing it would allow removing quite a lot of code (making the applet smaller) and test cases.

**Comment by guylouis** [comment]
I agree this is not needed anymore. Latest cards on the market implement KeyAgreement.ALG_EC_SVDP_DH_PLAIN_XY, and a smaller applet will make a quicker upload of the applet either at the factory or through the client side.

**Comment by bitgamma** [comment]
Ok, before adding much new code I am going to remove the old cruft then

**Comment by bitgamma** [comment]
Closed by e78397c19894d7931fc2ac5c407be441a9fdc32f
