### ISSUE TITLE
Implement on-card key generation & backup

### ISSUE THREAD

**Issue by bitgamma** [status-im/hardware-wallet#9]
Most wallets are using BIP39 with the mnemonic seed for backup/restore. This means that the key always leaves the device (having the user write it down on paper also counts as leaving the device) even for hardware wallets.

We must certainly support BIP39 (we do!), but we also need to allow generating keys on-card, with the ability to back them up to other cards.

After some discussion and thought, I have the following proposal which allows the user and/or wallet developer to choose the level of security desired and does not require trust of the issuer.

1) A backup session is started by the owner, who taps and authenticates with PIN to all cards partecipating (1 source and n targets) and specifies how many client devices will be used to generate entropy for the encryption key. It can be 1 (must be highly discouraged in UI) to X. The card will then accept exactly X pieces of entropy to be loaded. The device starting the backup also puts the first piece of entropy.

2) The owner taps the involved cards on the specified number of devices without any pairing or PIN authentication. Each device must generate one random 256-bit number and shot it to all cards using a one-shot secure channel (similar to what we do for the INIT APDU).  The card adds this number to its internal state. Using XOR to combine the state makes the order in which the taps happen irrelevant.

3) At the end of this procedure, all cards have the same piece of random information, but none of the client has more than 1 piece of the puzzle (unless a single client is being used).

4) The user than takes the source card and taps it to actually make a backup. This will require PIN entry authentication and will use the key generated following the procedure above. It will return the plain key uid, a random IV and the encrypted private master key and chain code. The backup key is then destroyed so further backups will require repeating the procedure.

5) The user will then tap and authenticate to all target cards which will receive the backup generated previously. The cards will decrypt the backup using the key generated previously and verify that the key UID matches. If it matches the key becomes the new master key of the card, which means the backup is succeful. Also in this case, the backup key is destroyed.

**Comment by ligi** [comment]
cc @nagydani

**Comment by bitgamma** [comment]
I am thinking the option of using 2 devices to perform the backup on the user side is the safest one and requires less trust. I can actually verify on-card that the device is a different one (at least, a different pairing key... doing a double pairing on the same device just to circumvent the security measure is less convenient that doing it right).

**Comment by bitgamma** [comment]
Regarding backup and restore, I will update the original issue with a refined proposal which goes more in details on how things happen

**Comment by corpetty** [comment]
I love the use of moving away from recovery phrases, and this procedure (at first glance) seems to mitigate most issues with trusting devices to perform the backup.  

Practically speaking, for an average user, how many devices are readily available to perform such a procedure (phone and desktop)?  This could start as functionality for people holding larger amounts of funds, which is prompted when a user stores past X amount, to remind them they should up their security game.  

To that point, the UX has to be on point to make this easy to understand, as most people don't understand the need for multiple clients.

**Comment by bitgamma** [comment]
> Practically speaking, for an average user, how many devices are readily available to perform such a procedure (phone and desktop)? This could start as functionality for people holding larger amounts of funds, which is prompted when a user stores past X amount, to remind them they should up their security game.

Except for the main client which needs to be paired and where user enters PIN, the other devices can be completely untrusted, so one can ask friends, family or collegues. Ideally it is matter of sitting together 5 minutes and doing this thing.

> To that point, the UX has to be on point to make this easy to understand, as most people don't understand the need for multiple clients.

You hit the nail on the head, UX is crucial for this work in the real world. From the card side I will make sure the minimal amount of user input is required, but the user interface must help with this. I think it is important for the UX to be easy if you want to assist someone in doing this procedure.
